INSERT INTO USER(first_name,last_name, email) VALUES ('Kline', 'Hewitt', 'klinehewitt@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Ashley', 'Nixon', 'ashleynixon@polarium.com');        
INSERT INTO USER(first_name,last_name, email) VALUES ('Benton', 'Graves', 'bentongraves@polarium.com');      
INSERT INTO USER(first_name,last_name, email) VALUES ('Susie', 'Vaughn', 'susievaughn@polarium.com');        
INSERT INTO USER(first_name,last_name, email) VALUES ('Marion', 'Maldonado', 'marionmaldonado@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lenora', 'Bond', 'lenorabond@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Hall', 'Case', 'hallcase@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Evans', 'Mcleod', 'evansmcleod@polarium.com');        
INSERT INTO USER(first_name,last_name, email) VALUES ('Patsy', 'Finch', 'patsyfinch@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lydia', 'David', 'lydiadavid@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Janna', 'Franks', 'jannafranks@polarium.com');        
INSERT INTO USER(first_name,last_name, email) VALUES ('Georgia', 'Moran', 'georgiamoran@polarium.com');      
INSERT INTO USER(first_name,last_name, email) VALUES ('Larson', 'Thornton', 'larsonthornton@polarium.com');  
INSERT INTO USER(first_name,last_name, email) VALUES ('Myrtle', 'Washington', 'myrtlewashington@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Jordan', 'Hunt', 'jordanhunt@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Polly', 'Figueroa', 'pollyfigueroa@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Cooley', 'Berger', 'cooleyberger@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Gilmore', 'Stark', 'gilmorestark@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Martha', 'Buchanan', 'marthabuchanan@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Butler', 'Cook', 'butlercook@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Valerie', 'Curtis', 'valeriecurtis@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Colette', 'Moody', 'colettemoody@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Laurel', 'Walton', 'laurelwalton@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Leonor', 'Merrill', 'leonormerrill@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Ola', 'Williams', 'olawilliams@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Thelma', 'Navarro', 'thelmanavarro@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Tisha', 'Mcclure', 'tishamcclure@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Danielle', 'Sears', 'daniellesears@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Ashley', 'Harding', 'ashleyharding@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Velma', 'Rodgers', 'velmarodgers@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Phyllis', 'Oneal', 'phyllisoneal@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Shelton', 'Olson', 'sheltonolson@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Alexandria', 'Santiago', 'alexandriasantiago@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Leonard', 'Ware', 'leonardware@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Juanita', 'Bartlett', 'juanitabartlett@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Conway', 'Pearson', 'conwaypearson@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Cote', 'Perez', 'coteperez@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Underwood', 'Langley', 'underwoodlangley@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Georgette', 'Mccarty', 'georgettemccarty@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Roach', 'Orr', 'roachorr@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Montoya', 'Michael', 'montoyamichael@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lee', 'Guy', 'leeguy@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Rose', 'Tucker', 'rosetucker@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Kramer', 'Frederick', 'kramerfrederick@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Donna', 'Lambert', 'donnalambert@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lynette', 'Hahn', 'lynettehahn@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Stephanie', 'Boyle', 'stephanieboyle@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Sybil', 'Lucas', 'sybillucas@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Wagner', 'Roman', 'wagnerroman@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Daisy', 'Compton', 'daisycompton@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Dawn', 'Norton', 'dawnnorton@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Pamela', 'Everett', 'pamelaeverett@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Obrien', 'Foley', 'obrienfoley@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('May', 'Caldwell', 'maycaldwell@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Tamara', 'Gross', 'tamaragross@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Ortiz', 'Valencia', 'ortizvalencia@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lilia', 'Black', 'liliablack@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Dianna', 'Schmidt', 'diannaschmidt@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Holman', 'Reynolds', 'holmanreynolds@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Thomas', 'Maxwell', 'thomasmaxwell@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Brooks', 'Bray', 'brooksbray@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Kellie', 'Rogers', 'kellierogers@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lucille', 'Johnston', 'lucillejohnston@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Mclean', 'Berry', 'mcleanberry@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Kate', 'Becker', 'katebecker@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Rita', 'Kane', 'ritakane@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Kristina', 'Bernard', 'kristinabernard@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Simpson', 'Blackburn', 'simpsonblackburn@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Catalina', 'Wilkerson', 'catalinawilkerson@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Amber', 'Fitzgerald', 'amberfitzgerald@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Cabrera', 'Lowe', 'cabreralowe@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Rachel', 'Pittman', 'rachelpittman@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Chandra', 'Montgomery', 'chandramontgomery@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Charlotte', 'Gill', 'charlottegill@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Burns', 'Estes', 'burnsestes@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Katina', 'Durham', 'katinadurham@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lesley', 'Zamora', 'lesleyzamora@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Mariana', 'Cooke', 'marianacooke@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Jessie', 'York', 'jessieyork@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Crosby', 'Mitchell', 'crosbymitchell@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Nolan', 'Vang', 'nolanvang@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Charity', 'Rutledge', 'charityrutledge@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Holt', 'Whitney', 'holtwhitney@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lucas', 'Kaufman', 'lucaskaufman@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Mcleod', 'Sharp', 'mcleodsharp@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Evangeline', 'Gregory', 'evangelinegregory@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Melva', 'Gilbert', 'melvagilbert@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Miranda', 'Gomez', 'mirandagomez@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Alma', 'Zimmerman', 'almazimmerman@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Holland', 'Stewart', 'hollandstewart@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Sasha', 'Craft', 'sashacraft@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Wolfe', 'Conway', 'wolfeconway@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Bishop', 'Cline', 'bishopcline@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Alta', 'Delaney', 'altadelaney@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Padilla', 'Brewer', 'padillabrewer@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Morrison', 'Sawyer', 'morrisonsawyer@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Cobb', 'Kirby', 'cobbkirby@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Emily', 'Golden', 'emilygolden@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Rose', 'Mills', 'rosemills@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Franklin', 'Vaughan', 'franklinvaughan@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Margarita', 'Newman', 'margaritanewman@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Roberts', 'Trujillo', 'robertstrujillo@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Francisca', 'Mullins', 'franciscamullins@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Young', 'Holder', 'youngholder@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Pope', 'Wade', 'popewade@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Cantu', 'Ferrell', 'cantuferrell@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Wilkinson', 'Skinner', 'wilkinsonskinner@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Jenna', 'Ochoa', 'jennaochoa@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Josephine', 'Flowers', 'josephineflowers@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Genevieve', 'Mcguire', 'genevievemcguire@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Margery', 'Griffith', 'margerygriffith@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Gena', 'Nguyen', 'genanguyen@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Banks', 'Blankenship', 'banksblankenship@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Kayla', 'Marsh', 'kaylamarsh@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Robert', 'Murphy', 'robertmurphy@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Gonzales', 'Schneider', 'gonzalesschneider@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Felicia', 'Duncan', 'feliciaduncan@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Jasmine', 'Jensen', 'jasminejensen@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Cornelia', 'Mckee', 'corneliamckee@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Chaney', 'Sloan', 'chaneysloan@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Bethany', 'Rios', 'bethanyrios@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lancaster', 'Carlson', 'lancastercarlson@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Carr', 'Decker', 'carrdecker@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Mejia', 'Church', 'mejiachurch@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Christy', 'Spencer', 'christyspencer@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lorie', 'Chen', 'loriechen@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Powell', 'Simpson', 'powellsimpson@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Ayala', 'Contreras', 'ayalacontreras@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Melton', 'Cannon', 'meltoncannon@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Marshall', 'Garrett', 'marshallgarrett@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Green', 'Sellers', 'greensellers@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Dominique', 'Cobb', 'dominiquecobb@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Blair', 'Bright', 'blairbright@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Mara', 'Elliott', 'maraelliott@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Wall', 'Reid', 'wallreid@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Tate', 'Robbins', 'taterobbins@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Sandoval', 'Morse', 'sandovalmorse@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Sweet', 'Shepard', 'sweetshepard@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Geraldine', 'Roy', 'geraldineroy@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Whitney', 'West', 'whitneywest@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Castro', 'Peters', 'castropeters@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Dee', 'Powell', 'deepowell@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Jeanne', 'Ratliff', 'jeanneratliff@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Clarissa', 'Lynn', 'clarissalynn@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Fletcher', 'Thomas', 'fletcherthomas@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Leta', 'Donaldson', 'letadonaldson@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Dorsey', 'Fisher', 'dorseyfisher@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Sosa', 'Hobbs', 'sosahobbs@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Henson', 'Bird', 'hensonbird@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Barry', 'Tate', 'barrytate@polarium.com');




INSERT INTO BOOK(title,stock) VALUES ('TestBook', '9');
INSERT INTO BOOK(title,stock) VALUES ('Sleepover', '20');
INSERT INTO BOOK(title,stock) VALUES ('Salvador', '3');
INSERT INTO BOOK(title,stock) VALUES ('Dona Flor and Her Two Husbands', '14');
INSERT INTO BOOK(title,stock) VALUES ('Two Thousand Maniacs!', '7');
INSERT INTO BOOK(title,stock) VALUES ('Tickle in the Heart, A', '6');
INSERT INTO BOOK(title,stock) VALUES ('Hilton!', '4');
INSERT INTO BOOK(title,stock) VALUES ('L.627', '5');
INSERT INTO BOOK(title,stock) VALUES ('Running With Scissors', '7');
INSERT INTO BOOK(title,stock) VALUES ('Marva Collins Story, The', '10');      
INSERT INTO BOOK(title,stock) VALUES ('Hannah Free', '15');
INSERT INTO BOOK(title,stock) VALUES ('Scarecrow, The', '8');
INSERT INTO BOOK(title,stock) VALUES ('A Good Lawyers Wife', '10');
INSERT INTO BOOK(title,stock) VALUES ('Dhobi Ghat', '17');
INSERT INTO BOOK(title,stock) VALUES ('Lee Destinees', '3');
INSERT INTO BOOK(title,stock) VALUES ('Fubar II: Balls to the Wall', '18');   
INSERT INTO BOOK(title,stock) VALUES ('Evil Dead, The', '19');
INSERT INTO BOOK(title,stock) VALUES ('City of Angels', '17');
INSERT INTO BOOK(title,stock) VALUES ('Things Change', '18');
INSERT INTO BOOK(title,stock) VALUES ('Young Guns', '10');
INSERT INTO BOOK(title,stock) VALUES ('W.R.: Mysteries of the Organism', '14');
INSERT INTO BOOK(title,stock) VALUES ('John Carter', '19');
INSERT INTO BOOK(title,stock) VALUES ('Morning Glory', '18');
INSERT INTO BOOK(title,stock) VALUES ('Shadows of Liberty ', '20');
INSERT INTO BOOK(title,stock) VALUES ('Babylon 5: In the Beginning', '3');
INSERT INTO BOOK(title,stock) VALUES ('How to Make an American Quilt', '4');
INSERT INTO BOOK(title,stock) VALUES ('Failure to Launch', '9');
INSERT INTO BOOK(title,stock) VALUES ('Boulevard', '6');
INSERT INTO BOOK(title,stock) VALUES ('Escape to Athena', '14');
INSERT INTO BOOK(title,stock) VALUES ('Roaring Twenties, The', '4');
INSERT INTO BOOK(title,stock) VALUES ('Night the Lights Went Out in Georgia, The', '13');
INSERT INTO BOOK(title,stock) VALUES ('Parasomnia', '3');
INSERT INTO BOOK(title,stock) VALUES ('Jungle Book, The', '9');
INSERT INTO BOOK(title,stock) VALUES ('Darling Lili', '19');
INSERT INTO BOOK(title,stock) VALUES ('Paths of Glory', '6');
INSERT INTO BOOK(title,stock) VALUES ('Joyriders, The', '20');
INSERT INTO BOOK(title,stock) VALUES ('Keys of the Kingdom, The', '12');
INSERT INTO BOOK(title,stock) VALUES ('Of Human Bondage', '18');
INSERT INTO BOOK(title,stock) VALUES ('Bye Bye Braverman', '13');
INSERT INTO BOOK(title,stock) VALUES ('The Adventures of André and Wally B.', '10');
INSERT INTO BOOK(title,stock) VALUES ('Rough Magic', '19');
INSERT INTO BOOK(title,stock) VALUES ('Never a Dull Moment', '9');
INSERT INTO BOOK(title,stock) VALUES ('Katt Williams: Priceless: Afterlife', '3');
INSERT INTO BOOK(title,stock) VALUES ('Time Walker Being From Another Planet', '20');
INSERT INTO BOOK(title,stock) VALUES ('Wild Bill', '19');
INSERT INTO BOOK(title,stock) VALUES ('Dad', '19');
INSERT INTO BOOK(title,stock) VALUES ('Howling V: The Rebirth', '20');
INSERT INTO BOOK(title,stock) VALUES ('District 13', '16');
INSERT INTO BOOK(title,stock) VALUES ('Otis', '1');
INSERT INTO BOOK(title,stock) VALUES ('The Face Behind the Mask', '4');
INSERT INTO BOOK(title,stock) VALUES ('Sundays and Cybele', '3');
INSERT INTO BOOK(title,stock) VALUES ('Two Men Went to War', '9');
INSERT INTO BOOK(title,stock) VALUES ('Smitty', '12');
INSERT INTO BOOK(title,stock) VALUES ('Slumber Party Massacre, The', '4');
INSERT INTO BOOK(title,stock) VALUES ('Man of the Century', '15');
INSERT INTO BOOK(title,stock) VALUES ('Paperhouse', '11');
INSERT INTO BOOK(title,stock) VALUES ('Hexed', '7');
INSERT INTO BOOK(title,stock) VALUES ('Banklady', '7');
INSERT INTO BOOK(title,stock) VALUES ('Dead Hate the Living!, The', '11');
INSERT INTO BOOK(title,stock) VALUES ('Citizen Dog', '7');
INSERT INTO BOOK(title,stock) VALUES ('C.H.O.M.P.S.', '9');
INSERT INTO BOOK(title,stock) VALUES ('Brothers Kiss, A', '15');
INSERT INTO BOOK(title,stock) VALUES ('Night at the Museum: Secret of the Tomb', '9');
INSERT INTO BOOK(title,stock) VALUES ('Letter, The', '6');
INSERT INTO BOOK(title,stock) VALUES ('Babymakers, The', '17');
INSERT INTO BOOK(title,stock) VALUES ('House Arrest', '18');
INSERT INTO BOOK(title,stock) VALUES ('Run, Man, Run!', '18');
INSERT INTO BOOK(title,stock) VALUES ('Dead of the Nite', '12');
INSERT INTO BOOK(title,stock) VALUES ('Simpsons Movie, The', '16');
INSERT INTO BOOK(title,stock) VALUES ('DEFCON: The Documentary', '17');
INSERT INTO BOOK(title,stock) VALUES ('Trailer Park of Terror', '18');
INSERT INTO BOOK(title,stock) VALUES ('Fade To Black', '4');
INSERT INTO BOOK(title,stock) VALUES ('Geographer Drank His Globe Away', '18');
INSERT INTO BOOK(title,stock) VALUES ('Mrs. Dalloway', '17');
INSERT INTO BOOK(title,stock) VALUES ('Black Cauldron, The', '7');
INSERT INTO BOOK(title,stock) VALUES ('My Friend Irma Goes West', '1');
INSERT INTO BOOK(title,stock) VALUES ('Shouting Fire: Stories from the Edge of Free Speech', '1');
INSERT INTO BOOK(title,stock) VALUES ('Dolly and Her Lover', '9');
INSERT INTO BOOK(title,stock) VALUES ('Blue Angel, The', '7');
INSERT INTO BOOK(title,stock) VALUES ('The Captains', '20');
INSERT INTO BOOK(title,stock) VALUES ('Stanley Kubrick: A Life in Pictures', '15');
INSERT INTO BOOK(title,stock) VALUES ('Dead Man', '16');
INSERT INTO BOOK(title,stock) VALUES ('Sister Helen ', '2');
INSERT INTO BOOK(title,stock) VALUES ('Swan and the Wanderer', '3');
INSERT INTO BOOK(title,stock) VALUES ('Hawaii', '16');
INSERT INTO BOOK(title,stock) VALUES ('Stalker', '2');
INSERT INTO BOOK(title,stock) VALUES ('Deja Vu', '19');
INSERT INTO BOOK(title,stock) VALUES ('Anna Karenina', '20');
INSERT INTO BOOK(title,stock) VALUES ('Maze, The', '11');
INSERT INTO BOOK(title,stock) VALUES ('61*', '17');
INSERT INTO BOOK(title,stock) VALUES ('Willard', '14');
INSERT INTO BOOK(title,stock) VALUES ('Good Wife, The', '4');
INSERT INTO BOOK(title,stock) VALUES ('Embodiment of Evil', '6');
INSERT INTO BOOK(title,stock) VALUES ('All at Sea', '7');
INSERT INTO BOOK(title,stock) VALUES ('Let Me In', '9');
INSERT INTO BOOK(title,stock) VALUES ('Suez', '15');
INSERT INTO BOOK(title,stock) VALUES ('Warriors of Virtue', '17');
INSERT INTO BOOK(title,stock) VALUES ('The Walking death', '20');
INSERT INTO BOOK(title,stock) VALUES ('Bohemian Life', '19');
INSERT INTO BOOK(title,stock) VALUES ('the Walking death', '14');
INSERT INTO BOOK(title,stock) VALUES ('sint consectetur', '0');
INSERT INTO BOOK(title,stock) VALUES ('aliqua in', '4');
INSERT INTO BOOK(title,stock) VALUES ('pariatur commodo', '3');
INSERT INTO BOOK(title,stock) VALUES ('commodo exercitation', '13');
INSERT INTO BOOK(title,stock) VALUES ('labore dolore', '11');
INSERT INTO BOOK(title,stock) VALUES ('laborum culpa', '3');
INSERT INTO BOOK(title,stock) VALUES ('nulla ad', '11');
INSERT INTO BOOK(title,stock) VALUES ('amet amet', '12');
INSERT INTO BOOK(title,stock) VALUES ('ea sunt', '0');
INSERT INTO BOOK(title,stock) VALUES ('eiusmod aute', '5');
INSERT INTO BOOK(title,stock) VALUES ('nulla cillum', '6');
INSERT INTO BOOK(title,stock) VALUES ('minim deserunt', '0');
INSERT INTO BOOK(title,stock) VALUES ('nulla ipsum', '13');
INSERT INTO BOOK(title,stock) VALUES ('veniam velit', '15');
INSERT INTO BOOK(title,stock) VALUES ('consequat ea', '14');
INSERT INTO BOOK(title,stock) VALUES ('laborum esse', '2');
INSERT INTO BOOK(title,stock) VALUES ('minim eu', '15');
INSERT INTO BOOK(title,stock) VALUES ('labore magna', '8');
INSERT INTO BOOK(title,stock) VALUES ('commodo dolor', '2');
INSERT INTO BOOK(title,stock) VALUES ('ipsum tempor', '1');
INSERT INTO BOOK(title,stock) VALUES ('duis anim', '7');
INSERT INTO BOOK(title,stock) VALUES ('officia sunt', '6');
INSERT INTO BOOK(title,stock) VALUES ('aliqua minim', '4');
INSERT INTO BOOK(title,stock) VALUES ('aliqua ad', '2');
INSERT INTO BOOK(title,stock) VALUES ('laboris tempor', '1');
INSERT INTO BOOK(title,stock) VALUES ('occaecat velit', '3');
INSERT INTO BOOK(title,stock) VALUES ('incididunt ad', '14');
INSERT INTO BOOK(title,stock) VALUES ('magna consectetur', '10');
INSERT INTO BOOK(title,stock) VALUES ('aliquip aliqua', '7');
INSERT INTO BOOK(title,stock) VALUES ('sit amet', '6');
INSERT INTO BOOK(title,stock) VALUES ('cillum Lorem', '13');
INSERT INTO BOOK(title,stock) VALUES ('laboris nisi', '5');
INSERT INTO BOOK(title,stock) VALUES ('sint amet', '1');
INSERT INTO BOOK(title,stock) VALUES ('ea qui', '12');
INSERT INTO BOOK(title,stock) VALUES ('dolore nostrud', '8');
INSERT INTO BOOK(title,stock) VALUES ('cupidatat sit', '10');
INSERT INTO BOOK(title,stock) VALUES ('amet laboris', '13');
INSERT INTO BOOK(title,stock) VALUES ('pariatur quis', '8');
INSERT INTO BOOK(title,stock) VALUES ('eiusmod labore', '13');
INSERT INTO BOOK(title,stock) VALUES ('culpa elit', '13');
INSERT INTO BOOK(title,stock) VALUES ('adipisicing duis', '1');
INSERT INTO BOOK(title,stock) VALUES ('est laborum', '13');
INSERT INTO BOOK(title,stock) VALUES ('eu non', '7');
INSERT INTO BOOK(title,stock) VALUES ('in non', '6');
INSERT INTO BOOK(title,stock) VALUES ('excepteur reprehenderit', '6');
INSERT INTO BOOK(title,stock) VALUES ('labore laboris', '5');
INSERT INTO BOOK(title,stock) VALUES ('veniam irure', '6');
INSERT INTO BOOK(title,stock) VALUES ('reprehenderit voluptate', '12');
INSERT INTO BOOK(title,stock) VALUES ('aliquip amet', '12');
INSERT INTO BOOK(title,stock) VALUES ('sint do', '3');




INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (145,69,'2022-7-17','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (8,94,'2022-8-12','renewal','on time');      
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (89,144,'2022-3-11','renewal','on delay');   
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (35,136,'2022-5-12','renewal','returned');   
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (62,47,'2022-4-15','renewal','returned');    
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (116,78,'2022-9-8','renewal','on time');     
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (45,22,'2022-10-10','borrowing','returned'); 
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (137,75,'2022-1-11','renewal','returned');   
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (134,65,'2022-10-15','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (91,101,'2022-6-8','borrowing','on time');   
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (33,104,'2022-7-12','renewal','returned');   
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (103,3,'2022-5-9','renewal','on delay');     
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (43,17,'2022-2-14','renewal','on delay');    
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (67,150,'2022-6-18','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (145,123,'2022-8-12','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (9,25,'2022-11-12','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (91,36,'2022-4-9','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (102,145,'2022-2-10','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (56,145,'2022-7-11','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (124,87,'2022-6-14','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (29,71,'2022-10-18','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (113,127,'2022-12-13','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (31,68,'2022-10-8','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (142,132,'2022-5-8','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (31,64,'2022-12-9','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (118,16,'2022-11-13','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (149,95,'2022-6-13','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (71,95,'2022-11-13','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (88,50,'2022-12-14','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (2,85,'2022-7-16','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (61,139,'2022-2-8','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (26,23,'2022-7-9','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (20,129,'2022-6-14','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (24,72,'2022-4-10','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (105,124,'2022-6-12','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (46,45,'2022-8-18','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (34,87,'2022-3-12','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (75,5,'2022-4-11','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (50,72,'2022-11-14','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (103,89,'2022-7-12','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (93,28,'2022-1-12','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (45,103,'2022-9-12','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (29,8,'2022-8-11','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (132,18,'2022-11-13','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (92,70,'2022-10-16','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (127,14,'2022-2-17','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (72,32,'2022-5-16','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (97,26,'2022-3-9','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (110,126,'2022-10-12','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (34,85,'2022-3-18','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (98,48,'2022-12-10','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (130,52,'2022-1-9','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (150,133,'2022-7-14','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (143,60,'2022-4-9','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (113,27,'2022-6-11','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (139,31,'2022-4-10','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (20,9,'2022-5-17','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (47,127,'2022-10-11','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (13,96,'2022-10-12','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (22,58,'2022-10-16','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (44,36,'2022-1-17','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (63,79,'2022-2-15','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (104,83,'2022-7-10','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (68,131,'2022-12-8','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (79,103,'2022-6-16','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (99,129,'2022-5-10','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (9,33,'2022-1-12','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (10,75,'2022-8-8','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (138,137,'2022-11-16','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (81,66,'2022-1-9','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (89,47,'2022-11-14','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (45,66,'2022-1-16','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (109,33,'2022-9-15','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (18,47,'2022-11-18','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (140,107,'2022-10-12','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (2,72,'2022-8-11','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (140,129,'2022-2-9','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (103,2,'2022-2-17','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (61,41,'2022-5-18','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (16,17,'2022-8-14','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (58,63,'2022-6-18','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (102,136,'2022-7-14','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (111,87,'2022-12-16','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (125,8,'2022-4-9','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (110,128,'2022-1-12','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (11,9,'2022-9-14','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (148,133,'2022-12-16','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (57,67,'2022-10-18','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (133,39,'2022-9-12','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (134,134,'2022-3-16','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (121,59,'2022-2-10','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (4,63,'2022-1-17','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (129,83,'2022-6-14','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (13,45,'2022-11-12','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (90,129,'2022-12-18','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (133,50,'2022-11-12','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (115,18,'2022-11-8','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (83,142,'2022-4-15','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (122,49,'2022-11-18','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (92,100,'2022-10-9','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (74,144,'2022-7-16','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (99,135,'2022-4-14','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (113,116,'2022-9-18','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (24,1,'2022-11-11','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (4,83,'2022-6-16','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (81,150,'2022-3-18','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (87,138,'2022-7-16','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (146,41,'2022-10-11','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (128,40,'2022-6-10','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (79,55,'2022-8-13','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (135,34,'2022-6-16','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (58,55,'2022-9-16','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (41,54,'2022-9-16','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (120,95,'2022-3-15','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (66,1,'2022-1-13','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (114,3,'2022-3-9','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (109,46,'2022-12-17','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (120,8,'2022-10-12','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (112,41,'2022-3-18','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (62,132,'2022-2-9','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (116,82,'2022-3-15','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (89,129,'2022-4-12','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (124,116,'2022-5-16','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (53,66,'2022-4-8','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (4,147,'2022-9-8','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (123,52,'2022-3-9','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (98,98,'2022-10-12','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (24,76,'2022-3-13','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (56,113,'2022-9-11','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (69,52,'2022-3-18','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (11,66,'2022-12-16','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (3,81,'2022-1-9','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (10,3,'2022-1-15','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (27,16,'2022-4-9','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (85,145,'2022-1-12','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (145,32,'2022-3-10','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (64,137,'2022-11-14','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (122,46,'2022-4-18','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (134,72,'2022-3-13','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (61,107,'2022-6-8','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (125,58,'2022-3-16','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (125,47,'2022-12-15','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (29,64,'2022-9-18','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (137,21,'2022-3-17','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (105,19,'2022-9-17','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (107,98,'2022-9-11','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (119,95,'2022-10-17','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (105,117,'2022-10-11','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (59,141,'2022-6-12','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (126,99,'2022-11-18','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (77,54,'2022-7-12','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (149,43,'2022-9-16','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (147,22,'2022-7-8','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (23,138,'2022-12-9','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (116,53,'2022-10-14','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (104,14,'2022-5-8','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (52,1,'2022-3-12','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (47,21,'2022-7-11','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (94,24,'2022-7-13','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (134,118,'2022-9-15','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (72,29,'2022-11-18','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (135,54,'2022-6-10','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (5,71,'2022-2-17','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (50,50,'2022-8-8','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (139,19,'2022-2-18','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (144,68,'2022-3-11','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (34,82,'2022-9-13','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (29,9,'2022-7-18','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (96,85,'2022-12-13','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (124,114,'2022-7-16','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (49,66,'2022-1-10','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (1,68,'2022-3-16','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (99,18,'2022-8-12','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (42,64,'2022-5-17','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (147,111,'2022-3-8','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (117,13,'2022-10-16','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (138,30,'2022-5-14','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (117,49,'2022-7-15','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (135,10,'2022-12-12','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (49,124,'2022-9-14','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (147,150,'2022-6-15','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (119,112,'2022-7-13','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (133,109,'2022-8-13','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (8,44,'2022-3-15','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (52,8,'2022-4-8','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (14,130,'2022-4-8','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (135,26,'2022-2-13','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (146,8,'2022-5-14','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (71,127,'2022-5-13','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (122,24,'2022-3-17','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (38,75,'2022-12-9','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (112,136,'2022-12-9','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (22,86,'2022-4-12','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (107,26,'2022-3-14','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (128,20,'2022-1-18','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (119,33,'2022-9-15','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (45,93,'2022-2-8','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (27,13,'2022-9-16','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (100,89,'2022-1-14','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (132,23,'2022-8-11','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (87,50,'2022-10-13','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (110,140,'2022-7-8','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (148,123,'2022-10-8','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (75,54,'2022-9-18','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (49,115,'2022-5-17','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (46,35,'2022-11-15','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (91,69,'2022-10-12','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (80,71,'2022-5-11','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (105,87,'2022-3-8','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (119,20,'2022-2-16','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (116,37,'2022-7-16','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (88,140,'2022-3-14','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (115,108,'2022-3-16','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (138,28,'2022-7-13','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (87,147,'2022-12-14','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (27,133,'2022-5-14','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (2,25,'2022-2-13','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (87,148,'2022-3-8','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (20,111,'2022-3-14','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (113,93,'2022-2-13','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (29,52,'2022-7-11','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (144,150,'2022-8-18','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (23,9,'2022-12-8','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (86,124,'2022-9-17','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (138,69,'2022-6-14','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (7,149,'2022-3-13','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (59,28,'2022-7-9','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (140,142,'2022-12-11','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (137,61,'2022-4-12','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (47,66,'2022-1-8','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (36,114,'2022-1-11','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (54,89,'2022-6-13','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (134,48,'2022-11-15','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (124,104,'2022-5-18','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (27,124,'2022-3-18','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (18,32,'2022-1-10','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (99,48,'2022-1-18','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (129,119,'2022-5-12','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (16,5,'2022-1-16','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (35,74,'2022-6-13','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (82,56,'2022-1-18','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (6,24,'2022-1-12','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (57,123,'2022-2-10','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (68,128,'2022-4-12','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (139,37,'2022-6-12','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (119,84,'2022-9-13','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (3,77,'2022-2-18','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (31,118,'2022-10-17','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (61,127,'2022-5-9','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (82,96,'2022-6-18','renewal','on delay');