INSERT INTO USER(first_name,last_name, email) VALUES ('Kline', 'Hewitt', 'klinehewitt@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Ashley', 'Nixon', 'ashleynixon@polarium.com');        
INSERT INTO USER(first_name,last_name, email) VALUES ('Benton', 'Graves', 'bentongraves@polarium.com');      
INSERT INTO USER(first_name,last_name, email) VALUES ('Susie', 'Vaughn', 'susievaughn@polarium.com');        
INSERT INTO USER(first_name,last_name, email) VALUES ('Marion', 'Maldonado', 'marionmaldonado@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lenora', 'Bond', 'lenorabond@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Hall', 'Case', 'hallcase@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Evans', 'Mcleod', 'evansmcleod@polarium.com');        
INSERT INTO USER(first_name,last_name, email) VALUES ('Patsy', 'Finch', 'patsyfinch@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lydia', 'David', 'lydiadavid@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Janna', 'Franks', 'jannafranks@polarium.com');        
INSERT INTO USER(first_name,last_name, email) VALUES ('Georgia', 'Moran', 'georgiamoran@polarium.com');      
INSERT INTO USER(first_name,last_name, email) VALUES ('Larson', 'Thornton', 'larsonthornton@polarium.com');  
INSERT INTO USER(first_name,last_name, email) VALUES ('Myrtle', 'Washington', 'myrtlewashington@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Jordan', 'Hunt', 'jordanhunt@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Polly', 'Figueroa', 'pollyfigueroa@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Cooley', 'Berger', 'cooleyberger@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Gilmore', 'Stark', 'gilmorestark@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Martha', 'Buchanan', 'marthabuchanan@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Butler', 'Cook', 'butlercook@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Valerie', 'Curtis', 'valeriecurtis@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Colette', 'Moody', 'colettemoody@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Laurel', 'Walton', 'laurelwalton@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Leonor', 'Merrill', 'leonormerrill@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Ola', 'Williams', 'olawilliams@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Thelma', 'Navarro', 'thelmanavarro@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Tisha', 'Mcclure', 'tishamcclure@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Danielle', 'Sears', 'daniellesears@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Ashley', 'Harding', 'ashleyharding@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Velma', 'Rodgers', 'velmarodgers@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Phyllis', 'Oneal', 'phyllisoneal@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Shelton', 'Olson', 'sheltonolson@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Alexandria', 'Santiago', 'alexandriasantiago@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Leonard', 'Ware', 'leonardware@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Juanita', 'Bartlett', 'juanitabartlett@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Conway', 'Pearson', 'conwaypearson@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Cote', 'Perez', 'coteperez@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Underwood', 'Langley', 'underwoodlangley@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Georgette', 'Mccarty', 'georgettemccarty@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Roach', 'Orr', 'roachorr@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Montoya', 'Michael', 'montoyamichael@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lee', 'Guy', 'leeguy@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Rose', 'Tucker', 'rosetucker@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Kramer', 'Frederick', 'kramerfrederick@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Donna', 'Lambert', 'donnalambert@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lynette', 'Hahn', 'lynettehahn@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Stephanie', 'Boyle', 'stephanieboyle@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Sybil', 'Lucas', 'sybillucas@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Wagner', 'Roman', 'wagnerroman@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Daisy', 'Compton', 'daisycompton@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Dawn', 'Norton', 'dawnnorton@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Pamela', 'Everett', 'pamelaeverett@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Obrien', 'Foley', 'obrienfoley@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('May', 'Caldwell', 'maycaldwell@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Tamara', 'Gross', 'tamaragross@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Ortiz', 'Valencia', 'ortizvalencia@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lilia', 'Black', 'liliablack@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Dianna', 'Schmidt', 'diannaschmidt@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Holman', 'Reynolds', 'holmanreynolds@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Thomas', 'Maxwell', 'thomasmaxwell@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Brooks', 'Bray', 'brooksbray@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Kellie', 'Rogers', 'kellierogers@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lucille', 'Johnston', 'lucillejohnston@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Mclean', 'Berry', 'mcleanberry@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Kate', 'Becker', 'katebecker@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Rita', 'Kane', 'ritakane@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Kristina', 'Bernard', 'kristinabernard@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Simpson', 'Blackburn', 'simpsonblackburn@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Catalina', 'Wilkerson', 'catalinawilkerson@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Amber', 'Fitzgerald', 'amberfitzgerald@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Cabrera', 'Lowe', 'cabreralowe@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Rachel', 'Pittman', 'rachelpittman@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Chandra', 'Montgomery', 'chandramontgomery@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Charlotte', 'Gill', 'charlottegill@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Burns', 'Estes', 'burnsestes@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Katina', 'Durham', 'katinadurham@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lesley', 'Zamora', 'lesleyzamora@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Mariana', 'Cooke', 'marianacooke@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Jessie', 'York', 'jessieyork@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Crosby', 'Mitchell', 'crosbymitchell@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Nolan', 'Vang', 'nolanvang@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Charity', 'Rutledge', 'charityrutledge@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Holt', 'Whitney', 'holtwhitney@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lucas', 'Kaufman', 'lucaskaufman@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Mcleod', 'Sharp', 'mcleodsharp@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Evangeline', 'Gregory', 'evangelinegregory@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Melva', 'Gilbert', 'melvagilbert@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Miranda', 'Gomez', 'mirandagomez@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Alma', 'Zimmerman', 'almazimmerman@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Holland', 'Stewart', 'hollandstewart@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Sasha', 'Craft', 'sashacraft@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Wolfe', 'Conway', 'wolfeconway@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Bishop', 'Cline', 'bishopcline@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Alta', 'Delaney', 'altadelaney@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Padilla', 'Brewer', 'padillabrewer@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Morrison', 'Sawyer', 'morrisonsawyer@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Cobb', 'Kirby', 'cobbkirby@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Emily', 'Golden', 'emilygolden@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Rose', 'Mills', 'rosemills@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Franklin', 'Vaughan', 'franklinvaughan@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Margarita', 'Newman', 'margaritanewman@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Roberts', 'Trujillo', 'robertstrujillo@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Francisca', 'Mullins', 'franciscamullins@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Young', 'Holder', 'youngholder@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Pope', 'Wade', 'popewade@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Cantu', 'Ferrell', 'cantuferrell@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Wilkinson', 'Skinner', 'wilkinsonskinner@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Jenna', 'Ochoa', 'jennaochoa@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Josephine', 'Flowers', 'josephineflowers@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Genevieve', 'Mcguire', 'genevievemcguire@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Margery', 'Griffith', 'margerygriffith@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Gena', 'Nguyen', 'genanguyen@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Banks', 'Blankenship', 'banksblankenship@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Kayla', 'Marsh', 'kaylamarsh@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Robert', 'Murphy', 'robertmurphy@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Gonzales', 'Schneider', 'gonzalesschneider@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Felicia', 'Duncan', 'feliciaduncan@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Jasmine', 'Jensen', 'jasminejensen@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Cornelia', 'Mckee', 'corneliamckee@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Chaney', 'Sloan', 'chaneysloan@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Bethany', 'Rios', 'bethanyrios@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lancaster', 'Carlson', 'lancastercarlson@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Carr', 'Decker', 'carrdecker@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Mejia', 'Church', 'mejiachurch@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Christy', 'Spencer', 'christyspencer@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lorie', 'Chen', 'loriechen@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Powell', 'Simpson', 'powellsimpson@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Ayala', 'Contreras', 'ayalacontreras@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Melton', 'Cannon', 'meltoncannon@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Marshall', 'Garrett', 'marshallgarrett@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Green', 'Sellers', 'greensellers@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Dominique', 'Cobb', 'dominiquecobb@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Blair', 'Bright', 'blairbright@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Mara', 'Elliott', 'maraelliott@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Wall', 'Reid', 'wallreid@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Tate', 'Robbins', 'taterobbins@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Sandoval', 'Morse', 'sandovalmorse@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Sweet', 'Shepard', 'sweetshepard@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Geraldine', 'Roy', 'geraldineroy@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Whitney', 'West', 'whitneywest@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Castro', 'Peters', 'castropeters@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Dee', 'Powell', 'deepowell@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Jeanne', 'Ratliff', 'jeanneratliff@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Clarissa', 'Lynn', 'clarissalynn@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Fletcher', 'Thomas', 'fletcherthomas@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Leta', 'Donaldson', 'letadonaldson@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Dorsey', 'Fisher', 'dorseyfisher@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Sosa', 'Hobbs', 'sosahobbs@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Henson', 'Bird', 'hensonbird@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Barry', 'Tate', 'barrytate@polarium.com');




INSERT INTO BOOK(title,stock) VALUES ('Last Days', '16');
INSERT INTO BOOK(title,stock) VALUES ('Drive Me Crazy', '5');
INSERT INTO BOOK(title,stock) VALUES ('Silent Scream, The', '14');
INSERT INTO BOOK(title,stock) VALUES ('Always Outnumbered', '17');
INSERT INTO BOOK(title,stock) VALUES ('Setup (Set Up)', '4');
INSERT INTO BOOK(title,stock) VALUES ('Daltry Calhoun', '17');
INSERT INTO BOOK(title,stock) VALUES ('Bait', '4');
INSERT INTO BOOK(title,stock) VALUES ('Final Cut', '7');
INSERT INTO BOOK(title,stock) VALUES ('Southbounders', '6');
INSERT INTO BOOK(title,stock) VALUES ('Hysterical Blindness', '7');
INSERT INTO BOOK(title,stock) VALUES ('Mackennas Gold', '16');
INSERT INTO BOOK(title,stock) VALUES ('Honey Pot, The', '17');
INSERT INTO BOOK(title,stock) VALUES ('Whore', '11');
INSERT INTO BOOK(title,stock) VALUES ('99 River Street', '13');
INSERT INTO BOOK(title,stock) VALUES ('One Missed Call (Chakushin ari)', '6');
INSERT INTO BOOK(title,stock) VALUES ('Azumi 2: Death or Love', '18');
INSERT INTO BOOK(title,stock) VALUES ('Paradise Canyon', '16');
INSERT INTO BOOK(title,stock) VALUES ('Paranormal Activity 3', '6');
INSERT INTO BOOK(title,stock) VALUES ('Cat and Dog', '17');
INSERT INTO BOOK(title,stock) VALUES ('Paper Lion', '7');
INSERT INTO BOOK(title,stock) VALUES ('CJ7 (Cheung Gong 7 hou)', '7');
INSERT INTO BOOK(title,stock) VALUES ('Mine Games', '20');
INSERT INTO BOOK(title,stock) VALUES ('Rebel, The (Le Rebelle)', '7');
INSERT INTO BOOK(title,stock) VALUES ('American Hardcore', '17');
INSERT INTO BOOK(title,stock) VALUES ('Acts of Worship ', '20');
INSERT INTO BOOK(title,stock) VALUES ('I Got Next', '8');
INSERT INTO BOOK(title,stock) VALUES ('Secret Ceremony', '17');
INSERT INTO BOOK(title,stock) VALUES ('Letter to Momo, A (Momo e no tegami)', '5');
INSERT INTO BOOK(title,stock) VALUES ('Defending Your Life', '14');
INSERT INTO BOOK(title,stock) VALUES ('Mother and Child', '17');
INSERT INTO BOOK(title,stock) VALUES ('The Adventure of Faustus Bidgood', '8');
INSERT INTO BOOK(title,stock) VALUES ('Two Mules for Sister Sara', '19');
INSERT INTO BOOK(title,stock) VALUES ('Miss Kicki', '9');
INSERT INTO BOOK(title,stock) VALUES ('Constantine', '18');
INSERT INTO BOOK(title,stock) VALUES ('It Started with Eve', '7');
INSERT INTO BOOK(title,stock) VALUES ('Ghost and Mr. Chicken, The', '14');
INSERT INTO BOOK(title,stock) VALUES ('Brother Bear', '9');
INSERT INTO BOOK(title,stock) VALUES ('Parting Glances', '13');
INSERT INTO BOOK(title,stock) VALUES ('Blacula', '9');
INSERT INTO BOOK(title,stock) VALUES ('Drug War (Du zhan)', '14');
INSERT INTO BOOK(title,stock) VALUES ('And Now My Love (Toute une vie)', '13');
INSERT INTO BOOK(title,stock) VALUES ('American Hustle', '13');
INSERT INTO BOOK(title,stock) VALUES ('The Duke of Burgundy', '19');
INSERT INTO BOOK(title,stock) VALUES ('Cabaret', '8');
INSERT INTO BOOK(title,stock) VALUES ('Happy Ending, The', '7');
INSERT INTO BOOK(title,stock) VALUES ('A True Mob Story', '18');
INSERT INTO BOOK(title,stock) VALUES ('Exorcist, The', '13');
INSERT INTO BOOK(title,stock) VALUES ('Rikyu', '18');
INSERT INTO BOOK(title,stock) VALUES ('Mean Season, The', '11');
INSERT INTO BOOK(title,stock) VALUES ('London After Midnight', '20');
INSERT INTO BOOK(title,stock) VALUES ('Fame High', '1');
INSERT INTO BOOK(title,stock) VALUES ('Ride', '6');
INSERT INTO BOOK(title,stock) VALUES ('Jonathan Rosenbaum, Present', '3');
INSERT INTO BOOK(title,stock) VALUES ('À laventure', '3');
INSERT INTO BOOK(title,stock) VALUES ('Long Hello and Short Goodbye', '7');
INSERT INTO BOOK(title,stock) VALUES ('Christmas Evil (a.k.a. You Better Watch Out)', '19');
INSERT INTO BOOK(title,stock) VALUES ('Back from Eternity', '20');
INSERT INTO BOOK(title,stock) VALUES ('Agnes of God', '11');
INSERT INTO BOOK(title,stock) VALUES ('Raisin in the Sun, A', '2');
INSERT INTO BOOK(title,stock) VALUES ('Next of Kin', '16');
INSERT INTO BOOK(title,stock) VALUES ('Traffic', '13');
INSERT INTO BOOK(title,stock) VALUES ('Cross: The Arthur Blessitt Story, The', '4');
INSERT INTO BOOK(title,stock) VALUES ('What Did the Lady Forget? (Shukujo wa nani o wasureta ka) ', '7');
INSERT INTO BOOK(title,stock) VALUES ('F/X2 (a.k.a. F/X 2 - The Deadly Art of Illusion)', '20');
INSERT INTO BOOK(title,stock) VALUES ('Relative Strangers', '6');
INSERT INTO BOOK(title,stock) VALUES ('There Was a Father (Chichi ariki)', '10');
INSERT INTO BOOK(title,stock) VALUES ('Stand Up Guys', '16');
INSERT INTO BOOK(title,stock) VALUES ('Big Daddy', '8');
INSERT INTO BOOK(title,stock) VALUES ('Silent One, The', '3');
INSERT INTO BOOK(title,stock) VALUES ('No Way Out', '12');
INSERT INTO BOOK(title,stock) VALUES ('Face of Another, The (Tanin no kao)', '16');
INSERT INTO BOOK(title,stock) VALUES ('Breaking the Rules', '6');
INSERT INTO BOOK(title,stock) VALUES ('4 Months, 3 Weeks and 2 Days (4 luni, 3 saptamâni si 2 zile)', '1');
INSERT INTO BOOK(title,stock) VALUES ('Liberty Heights', '13');
INSERT INTO BOOK(title,stock) VALUES ('Waynes World 2', '2');
INSERT INTO BOOK(title,stock) VALUES ('Lorna', '13');
INSERT INTO BOOK(title,stock) VALUES ('Cutter, The', '20');
INSERT INTO BOOK(title,stock) VALUES ('Cannibal Holocaust', '8');
INSERT INTO BOOK(title,stock) VALUES ('Magic in the Water', '17');
INSERT INTO BOOK(title,stock) VALUES ('Breathe In', '19');
INSERT INTO BOOK(title,stock) VALUES ('My Fake  Fiance', '18');
INSERT INTO BOOK(title,stock) VALUES ('Another Mans Poison', '6');
INSERT INTO BOOK(title,stock) VALUES ('Poltergeist II: The Other Side', '6');
INSERT INTO BOOK(title,stock) VALUES ('Man of the West', '14');
INSERT INTO BOOK(title,stock) VALUES ('Father of the Bride', '13');
INSERT INTO BOOK(title,stock) VALUES ('Thieves Like Us', '3');
INSERT INTO BOOK(title,stock) VALUES ('Sea Wolf, The', '11');
INSERT INTO BOOK(title,stock) VALUES ('I Dont Want to Sleep Alone', '16');
INSERT INTO BOOK(title,stock) VALUES ('The Mark of Cain', '13');
INSERT INTO BOOK(title,stock) VALUES ('Agora', '12');
INSERT INTO BOOK(title,stock) VALUES ('George Carlin: Its Bad for Ya!', '4');
INSERT INTO BOOK(title,stock) VALUES ('Budd Boetticher: A Man Can Do That', '6');
INSERT INTO BOOK(title,stock) VALUES ('Things I Never Told You', '17');
INSERT INTO BOOK(title,stock) VALUES ('Café de Flore', '15');
INSERT INTO BOOK(title,stock) VALUES ('Riding in Cars with Boys', '6');
INSERT INTO BOOK(title,stock) VALUES ('Ama lur', '5');
INSERT INTO BOOK(title,stock) VALUES ('Smiley Face', '7');
INSERT INTO BOOK(title,stock) VALUES ('At Swords Point', '3');
INSERT INTO BOOK(title,stock) VALUES ('Mitchell', '8');
INSERT INTO BOOK(title,stock) VALUES ('Librarian: Return to King Solomons Mines, The', '6');
INSERT INTO BOOK(title,stock) VALUES ('The Life of Oharu', '18');
INSERT INTO BOOK(title,stock) VALUES ('Meteor', '8');
INSERT INTO BOOK(title,stock) VALUES ('The Closet', '16');
INSERT INTO BOOK(title,stock) VALUES ('Cant Help Singing', '1');
INSERT INTO BOOK(title,stock) VALUES ('American Son', '10');
INSERT INTO BOOK(title,stock) VALUES ('Tremors II: Aftershocks', '16');
INSERT INTO BOOK(title,stock) VALUES ('Jimi Hendrix', '10');
INSERT INTO BOOK(title,stock) VALUES ('Charlie Chan Carries On', '6');
INSERT INTO BOOK(title,stock) VALUES ('Im Gonna Git You Sucka', '3');
INSERT INTO BOOK(title,stock) VALUES ('Way... Way Out', '1');
INSERT INTO BOOK(title,stock) VALUES ('Direct Contact', '2');
INSERT INTO BOOK(title,stock) VALUES ('Mrs. Pollifax-Spy', '18');
INSERT INTO BOOK(title,stock) VALUES ('Totally F***ed Up', '9');
INSERT INTO BOOK(title,stock) VALUES ('History of Violence, A', '14');
INSERT INTO BOOK(title,stock) VALUES ('Girl of the Golden West', '11');
INSERT INTO BOOK(title,stock) VALUES ('Buckskin Frontier', '18');
INSERT INTO BOOK(title,stock) VALUES ('The Witches', '10');
INSERT INTO BOOK(title,stock) VALUES ('Boricuas Bond', '1');
INSERT INTO BOOK(title,stock) VALUES ('Mike Bassett: England Manager', '2');
INSERT INTO BOOK(title,stock) VALUES ('Thing: Terror Takes Shape, The', '1');
INSERT INTO BOOK(title,stock) VALUES ('The Walking Dead', '9');
INSERT INTO BOOK(title,stock) VALUES ('Oranges and Sunshine', '5');
INSERT INTO BOOK(title,stock) VALUES ('Jay and Silent Bob Strike Back', '2');
INSERT INTO BOOK(title,stock) VALUES ('Yes: 9012 Live', '4');
INSERT INTO BOOK(title,stock) VALUES ('Theodora Goes Wild', '11');
INSERT INTO BOOK(title,stock) VALUES ('Mermaids', '19');
INSERT INTO BOOK(title,stock) VALUES ('My Darling Clementine', '13');
INSERT INTO BOOK(title,stock) VALUES ('Sergeant Rutledge', '2');
INSERT INTO BOOK(title,stock) VALUES ('Masquerade', '1');
INSERT INTO BOOK(title,stock) VALUES ('Vampire Bat, The', '8');
INSERT INTO BOOK(title,stock) VALUES ('Brother (Hermano)', '13');
INSERT INTO BOOK(title,stock) VALUES ('King Corn', '2');
INSERT INTO BOOK(title,stock) VALUES ('Dogfight', '9');
INSERT INTO BOOK(title,stock) VALUES ('Shes So Lovely', '3');
INSERT INTO BOOK(title,stock) VALUES ('Beyond Borders', '14');
INSERT INTO BOOK(title,stock) VALUES ('Last Horror Movie, The', '8');
INSERT INTO BOOK(title,stock) VALUES ('Crimson Petal and the White, The', '20');
INSERT INTO BOOK(title,stock) VALUES ('My First Mister', '17');
INSERT INTO BOOK(title,stock) VALUES ('Spawn', '19');
INSERT INTO BOOK(title,stock) VALUES ('Summer in Berlin (Sommer vorm Balkon)', '16');
INSERT INTO BOOK(title,stock) VALUES ('Jennifers Body', '12');
INSERT INTO BOOK(title,stock) VALUES ('Alexander Nevsky (Aleksandr Nevskiy)', '11');
INSERT INTO BOOK(title,stock) VALUES ('Zebra Lounge', '19');
INSERT INTO BOOK(title,stock) VALUES ('Arcana', '10');
INSERT INTO BOOK(title,stock) VALUES ('Jonestown: The Life and Death of Peoples Temple', '19');
INSERT INTO BOOK(title,stock) VALUES ('Hangover, The', '11');
INSERT INTO BOOK(title,stock) VALUES ('Prince of the City', '15');
INSERT INTO BOOK(title,stock) VALUES ('Bad Luck (Zezowate szczescie)', '3');
INSERT INTO BOOK(title,stock) VALUES ('Colour of Magic, The (Terry Pratchetts The Colour of Magic)', '20');
INSERT INTO BOOK(title,stock) VALUES ('Godzilla vs. The Sea Monster (Gojira-Ebira-Mosura: Nankai no daiketto)', '8');
INSERT INTO BOOK(title,stock) VALUES ('Dirties, The', '14');
INSERT INTO BOOK(title,stock) VALUES ('Three Crowns of the Sailor (Les trois couronnes du matelot)', '17');
INSERT INTO BOOK(title,stock) VALUES ('WWII IN HD', '3');
INSERT INTO BOOK(title,stock) VALUES ('Rampage', '8');
INSERT INTO BOOK(title,stock) VALUES ('Lentsu', '10');
INSERT INTO BOOK(title,stock) VALUES ('Billy Blazes, Esq.', '15');
INSERT INTO BOOK(title,stock) VALUES ('Blues in the Night', '1');
INSERT INTO BOOK(title,stock) VALUES ('Palestine Is Still the Issue', '9');
INSERT INTO BOOK(title,stock) VALUES ('Aspen', '16');
INSERT INTO BOOK(title,stock) VALUES ('Electrick Children', '7');
INSERT INTO BOOK(title,stock) VALUES ('Great Ziegfeld, The', '18');
INSERT INTO BOOK(title,stock) VALUES ('Mrs. Brown (a.k.a. Her Majesty, Mrs. Brown)', '20');
INSERT INTO BOOK(title,stock) VALUES ('Loves Labours Lost', '18');
INSERT INTO BOOK(title,stock) VALUES ('Choose', '18');
INSERT INTO BOOK(title,stock) VALUES ('Popatopolis', '4');
INSERT INTO BOOK(title,stock) VALUES ('Rope', '11');
INSERT INTO BOOK(title,stock) VALUES ('The Pee-Wee Herman Show on Broadway', '4');
INSERT INTO BOOK(title,stock) VALUES ('To Be Takei', '16');
INSERT INTO BOOK(title,stock) VALUES ('Talent for the Game', '12');
INSERT INTO BOOK(title,stock) VALUES ('Critical Care', '14');
INSERT INTO BOOK(title,stock) VALUES ('Carlitos Way: Rise to Power (Carlitos Way 2: Rise to Power)', '10');
INSERT INTO BOOK(title,stock) VALUES ('Set Me Free (Emporte-moi)', '2');
INSERT INTO BOOK(title,stock) VALUES ('Alila', '12');
INSERT INTO BOOK(title,stock) VALUES ('Day of the Beast, The (Día de la Bestia, El)', '11');
INSERT INTO BOOK(title,stock) VALUES ('Measuring the World (Die Vermessung der Welt)', '20');
INSERT INTO BOOK(title,stock) VALUES ('Secret Agent, The', '6');
INSERT INTO BOOK(title,stock) VALUES ('A Lesson Before Dying', '18');
INSERT INTO BOOK(title,stock) VALUES ('War Is Over, The (Guerre est finie, La)', '5');
INSERT INTO BOOK(title,stock) VALUES ('The Fox & the Child', '18');
INSERT INTO BOOK(title,stock) VALUES ('Devils Trap, The (Dáblova past)', '1');
INSERT INTO BOOK(title,stock) VALUES ('Car 54, Where Are You?', '14');
INSERT INTO BOOK(title,stock) VALUES ('Riptide', '19');
INSERT INTO BOOK(title,stock) VALUES ('Late Phases', '6');
INSERT INTO BOOK(title,stock) VALUES ('Someones Watching Me!', '18');
INSERT INTO BOOK(title,stock) VALUES ('Ali', '14');
INSERT INTO BOOK(title,stock) VALUES ('Le créateur ', '20');
INSERT INTO BOOK(title,stock) VALUES ('Bertsolari', '13');
INSERT INTO BOOK(title,stock) VALUES ('Phantasm II', '17');
INSERT INTO BOOK(title,stock) VALUES ('Like Mike', '12');
INSERT INTO BOOK(title,stock) VALUES ('Proposition, The', '14');
INSERT INTO BOOK(title,stock) VALUES ('Sinivalkoinen valhe', '12');
INSERT INTO BOOK(title,stock) VALUES ('Elusive Summer of 68, The (Varljivo leto 68)', '4');
INSERT INTO BOOK(title,stock) VALUES ('June & Moon', '8');
INSERT INTO BOOK(title,stock) VALUES ('Love Affair', '17');
INSERT INTO BOOK(title,stock) VALUES ('Play it to the Bone', '8');
INSERT INTO BOOK(title,stock) VALUES ('Wyrmwood', '12');
INSERT INTO BOOK(title,stock) VALUES ('Meet the Applegates', '11');
INSERT INTO BOOK(title,stock) VALUES ('City in the Sea', '2');
INSERT INTO BOOK(title,stock) VALUES ('Wu Tang Master', '14');
INSERT INTO BOOK(title,stock) VALUES ('Latter Days', '16');




INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (145,69,'2022-7-17','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (8,94,'2022-8-12','renewal','on time');      
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (89,144,'2022-3-11','renewal','on delay');   
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (35,136,'2022-5-12','renewal','returned');   
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (62,47,'2022-4-15','renewal','returned');    
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (116,78,'2022-9-8','renewal','on time');     
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (45,22,'2022-10-10','borrowing','returned'); 
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (137,75,'2022-1-11','renewal','returned');   
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (134,65,'2022-10-15','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (91,101,'2022-6-8','borrowing','on time');   
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (33,104,'2022-7-12','renewal','returned');   
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (103,3,'2022-5-9','renewal','on delay');     
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (43,17,'2022-2-14','renewal','on delay');    
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (67,150,'2022-6-18','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (145,123,'2022-8-12','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (9,25,'2022-11-12','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (91,36,'2022-4-9','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (102,145,'2022-2-10','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (56,145,'2022-7-11','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (124,87,'2022-6-14','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (29,71,'2022-10-18','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (113,127,'2022-12-13','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (31,68,'2022-10-8','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (142,132,'2022-5-8','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (31,64,'2022-12-9','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (118,16,'2022-11-13','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (149,95,'2022-6-13','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (71,95,'2022-11-13','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (88,50,'2022-12-14','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (2,85,'2022-7-16','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (61,139,'2022-2-8','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (26,23,'2022-7-9','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (20,129,'2022-6-14','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (24,72,'2022-4-10','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (105,124,'2022-6-12','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (46,45,'2022-8-18','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (34,87,'2022-3-12','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (75,5,'2022-4-11','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (50,72,'2022-11-14','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (103,89,'2022-7-12','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (93,28,'2022-1-12','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (45,103,'2022-9-12','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (29,8,'2022-8-11','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (132,18,'2022-11-13','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (92,70,'2022-10-16','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (127,14,'2022-2-17','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (72,32,'2022-5-16','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (97,26,'2022-3-9','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (110,126,'2022-10-12','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (34,85,'2022-3-18','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (98,48,'2022-12-10','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (130,52,'2022-1-9','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (150,133,'2022-7-14','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (143,60,'2022-4-9','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (113,27,'2022-6-11','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (139,31,'2022-4-10','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (20,9,'2022-5-17','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (47,127,'2022-10-11','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (13,96,'2022-10-12','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (22,58,'2022-10-16','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (44,36,'2022-1-17','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (63,79,'2022-2-15','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (104,83,'2022-7-10','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (68,131,'2022-12-8','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (79,103,'2022-6-16','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (99,129,'2022-5-10','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (9,33,'2022-1-12','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (10,75,'2022-8-8','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (138,137,'2022-11-16','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (81,66,'2022-1-9','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (89,47,'2022-11-14','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (45,66,'2022-1-16','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (109,33,'2022-9-15','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (18,47,'2022-11-18','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (140,107,'2022-10-12','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (2,72,'2022-8-11','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (140,129,'2022-2-9','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (103,2,'2022-2-17','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (61,41,'2022-5-18','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (16,17,'2022-8-14','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (58,63,'2022-6-18','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (102,136,'2022-7-14','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (111,87,'2022-12-16','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (125,8,'2022-4-9','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (110,128,'2022-1-12','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (11,9,'2022-9-14','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (148,133,'2022-12-16','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (57,67,'2022-10-18','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (133,39,'2022-9-12','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (134,134,'2022-3-16','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (121,59,'2022-2-10','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (4,63,'2022-1-17','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (129,83,'2022-6-14','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (13,45,'2022-11-12','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (90,129,'2022-12-18','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (133,50,'2022-11-12','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (115,18,'2022-11-8','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (83,142,'2022-4-15','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (122,49,'2022-11-18','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (92,100,'2022-10-9','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (74,144,'2022-7-16','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (99,135,'2022-4-14','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (113,116,'2022-9-18','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (24,1,'2022-11-11','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (4,83,'2022-6-16','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (81,150,'2022-3-18','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (87,138,'2022-7-16','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (146,41,'2022-10-11','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (128,40,'2022-6-10','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (79,55,'2022-8-13','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (135,34,'2022-6-16','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (58,55,'2022-9-16','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (41,54,'2022-9-16','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (120,95,'2022-3-15','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (66,1,'2022-1-13','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (114,3,'2022-3-9','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (109,46,'2022-12-17','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (120,8,'2022-10-12','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (112,41,'2022-3-18','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (62,132,'2022-2-9','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (116,82,'2022-3-15','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (89,129,'2022-4-12','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (124,116,'2022-5-16','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (53,66,'2022-4-8','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (4,147,'2022-9-8','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (123,52,'2022-3-9','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (98,98,'2022-10-12','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (24,76,'2022-3-13','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (56,113,'2022-9-11','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (69,52,'2022-3-18','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (11,66,'2022-12-16','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (3,81,'2022-1-9','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (10,3,'2022-1-15','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (27,16,'2022-4-9','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (85,145,'2022-1-12','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (145,32,'2022-3-10','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (64,137,'2022-11-14','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (122,46,'2022-4-18','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (134,72,'2022-3-13','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (61,107,'2022-6-8','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (125,58,'2022-3-16','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (125,47,'2022-12-15','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (29,64,'2022-9-18','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (137,21,'2022-3-17','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (105,19,'2022-9-17','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (107,98,'2022-9-11','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (119,95,'2022-10-17','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (105,117,'2022-10-11','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (59,141,'2022-6-12','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (126,99,'2022-11-18','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (77,54,'2022-7-12','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (149,43,'2022-9-16','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (147,22,'2022-7-8','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (23,138,'2022-12-9','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (116,53,'2022-10-14','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (104,14,'2022-5-8','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (52,1,'2022-3-12','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (47,21,'2022-7-11','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (94,24,'2022-7-13','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (134,118,'2022-9-15','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (72,29,'2022-11-18','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (135,54,'2022-6-10','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (5,71,'2022-2-17','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (50,50,'2022-8-8','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (139,19,'2022-2-18','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (144,68,'2022-3-11','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (34,82,'2022-9-13','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (29,9,'2022-7-18','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (96,85,'2022-12-13','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (124,114,'2022-7-16','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (49,66,'2022-1-10','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (1,68,'2022-3-16','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (99,18,'2022-8-12','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (42,64,'2022-5-17','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (147,111,'2022-3-8','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (117,13,'2022-10-16','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (138,30,'2022-5-14','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (117,49,'2022-7-15','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (135,10,'2022-12-12','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (49,124,'2022-9-14','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (147,150,'2022-6-15','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (119,112,'2022-7-13','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (133,109,'2022-8-13','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (8,44,'2022-3-15','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (52,8,'2022-4-8','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (14,130,'2022-4-8','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (135,26,'2022-2-13','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (146,8,'2022-5-14','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (71,127,'2022-5-13','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (122,24,'2022-3-17','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (38,75,'2022-12-9','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (112,136,'2022-12-9','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (22,86,'2022-4-12','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (107,26,'2022-3-14','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (128,20,'2022-1-18','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (119,33,'2022-9-15','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (45,93,'2022-2-8','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (27,13,'2022-9-16','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (100,89,'2022-1-14','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (132,23,'2022-8-11','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (87,50,'2022-10-13','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (110,140,'2022-7-8','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (148,123,'2022-10-8','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (75,54,'2022-9-18','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (49,115,'2022-5-17','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (46,35,'2022-11-15','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (91,69,'2022-10-12','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (80,71,'2022-5-11','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (105,87,'2022-3-8','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (119,20,'2022-2-16','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (116,37,'2022-7-16','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (88,140,'2022-3-14','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (115,108,'2022-3-16','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (138,28,'2022-7-13','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (87,147,'2022-12-14','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (27,133,'2022-5-14','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (2,25,'2022-2-13','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (87,148,'2022-3-8','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (20,111,'2022-3-14','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (113,93,'2022-2-13','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (29,52,'2022-7-11','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (144,150,'2022-8-18','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (23,9,'2022-12-8','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (86,124,'2022-9-17','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (138,69,'2022-6-14','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (7,149,'2022-3-13','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (59,28,'2022-7-9','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (140,142,'2022-12-11','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (137,61,'2022-4-12','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (47,66,'2022-1-8','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (36,114,'2022-1-11','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (54,89,'2022-6-13','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (134,48,'2022-11-15','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (124,104,'2022-5-18','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (27,124,'2022-3-18','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (18,32,'2022-1-10','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (99,48,'2022-1-18','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (129,119,'2022-5-12','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (16,5,'2022-1-16','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (35,74,'2022-6-13','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (82,56,'2022-1-18','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (6,24,'2022-1-12','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (57,123,'2022-2-10','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (68,128,'2022-4-12','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (139,37,'2022-6-12','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (119,84,'2022-9-13','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (3,77,'2022-2-18','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (31,118,'2022-10-17','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (61,127,'2022-5-9','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (82,96,'2022-6-18','renewal','on delay');