INSERT INTO USER(first_name,last_name, email) VALUES ('Kline', 'Hewitt', 'klinehewitt@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Ashley', 'Nixon', 'ashleynixon@polarium.com');        
INSERT INTO USER(first_name,last_name, email) VALUES ('Benton', 'Graves', 'bentongraves@polarium.com');      
INSERT INTO USER(first_name,last_name, email) VALUES ('Susie', 'Vaughn', 'susievaughn@polarium.com');        
INSERT INTO USER(first_name,last_name, email) VALUES ('Marion', 'Maldonado', 'marionmaldonado@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lenora', 'Bond', 'lenorabond@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Hall', 'Case', 'hallcase@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Evans', 'Mcleod', 'evansmcleod@polarium.com');        
INSERT INTO USER(first_name,last_name, email) VALUES ('Patsy', 'Finch', 'patsyfinch@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lydia', 'David', 'lydiadavid@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Janna', 'Franks', 'jannafranks@polarium.com');        
INSERT INTO USER(first_name,last_name, email) VALUES ('Georgia', 'Moran', 'georgiamoran@polarium.com');      
INSERT INTO USER(first_name,last_name, email) VALUES ('Larson', 'Thornton', 'larsonthornton@polarium.com');  
INSERT INTO USER(first_name,last_name, email) VALUES ('Myrtle', 'Washington', 'myrtlewashington@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Jordan', 'Hunt', 'jordanhunt@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Polly', 'Figueroa', 'pollyfigueroa@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Cooley', 'Berger', 'cooleyberger@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Gilmore', 'Stark', 'gilmorestark@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Martha', 'Buchanan', 'marthabuchanan@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Butler', 'Cook', 'butlercook@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Valerie', 'Curtis', 'valeriecurtis@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Colette', 'Moody', 'colettemoody@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Laurel', 'Walton', 'laurelwalton@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Leonor', 'Merrill', 'leonormerrill@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Ola', 'Williams', 'olawilliams@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Thelma', 'Navarro', 'thelmanavarro@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Tisha', 'Mcclure', 'tishamcclure@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Danielle', 'Sears', 'daniellesears@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Ashley', 'Harding', 'ashleyharding@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Velma', 'Rodgers', 'velmarodgers@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Phyllis', 'Oneal', 'phyllisoneal@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Shelton', 'Olson', 'sheltonolson@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Alexandria', 'Santiago', 'alexandriasantiago@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Leonard', 'Ware', 'leonardware@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Juanita', 'Bartlett', 'juanitabartlett@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Conway', 'Pearson', 'conwaypearson@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Cote', 'Perez', 'coteperez@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Underwood', 'Langley', 'underwoodlangley@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Georgette', 'Mccarty', 'georgettemccarty@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Roach', 'Orr', 'roachorr@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Montoya', 'Michael', 'montoyamichael@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lee', 'Guy', 'leeguy@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Rose', 'Tucker', 'rosetucker@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Kramer', 'Frederick', 'kramerfrederick@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Donna', 'Lambert', 'donnalambert@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lynette', 'Hahn', 'lynettehahn@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Stephanie', 'Boyle', 'stephanieboyle@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Sybil', 'Lucas', 'sybillucas@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Wagner', 'Roman', 'wagnerroman@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Daisy', 'Compton', 'daisycompton@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Dawn', 'Norton', 'dawnnorton@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Pamela', 'Everett', 'pamelaeverett@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Obrien', 'Foley', 'obrienfoley@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('May', 'Caldwell', 'maycaldwell@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Tamara', 'Gross', 'tamaragross@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Ortiz', 'Valencia', 'ortizvalencia@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lilia', 'Black', 'liliablack@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Dianna', 'Schmidt', 'diannaschmidt@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Holman', 'Reynolds', 'holmanreynolds@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Thomas', 'Maxwell', 'thomasmaxwell@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Brooks', 'Bray', 'brooksbray@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Kellie', 'Rogers', 'kellierogers@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lucille', 'Johnston', 'lucillejohnston@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Mclean', 'Berry', 'mcleanberry@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Kate', 'Becker', 'katebecker@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Rita', 'Kane', 'ritakane@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Kristina', 'Bernard', 'kristinabernard@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Simpson', 'Blackburn', 'simpsonblackburn@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Catalina', 'Wilkerson', 'catalinawilkerson@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Amber', 'Fitzgerald', 'amberfitzgerald@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Cabrera', 'Lowe', 'cabreralowe@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Rachel', 'Pittman', 'rachelpittman@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Chandra', 'Montgomery', 'chandramontgomery@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Charlotte', 'Gill', 'charlottegill@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Burns', 'Estes', 'burnsestes@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Katina', 'Durham', 'katinadurham@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lesley', 'Zamora', 'lesleyzamora@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Mariana', 'Cooke', 'marianacooke@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Jessie', 'York', 'jessieyork@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Crosby', 'Mitchell', 'crosbymitchell@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Nolan', 'Vang', 'nolanvang@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Charity', 'Rutledge', 'charityrutledge@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Holt', 'Whitney', 'holtwhitney@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lucas', 'Kaufman', 'lucaskaufman@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Mcleod', 'Sharp', 'mcleodsharp@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Evangeline', 'Gregory', 'evangelinegregory@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Melva', 'Gilbert', 'melvagilbert@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Miranda', 'Gomez', 'mirandagomez@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Alma', 'Zimmerman', 'almazimmerman@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Holland', 'Stewart', 'hollandstewart@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Sasha', 'Craft', 'sashacraft@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Wolfe', 'Conway', 'wolfeconway@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Bishop', 'Cline', 'bishopcline@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Alta', 'Delaney', 'altadelaney@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Padilla', 'Brewer', 'padillabrewer@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Morrison', 'Sawyer', 'morrisonsawyer@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Cobb', 'Kirby', 'cobbkirby@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Emily', 'Golden', 'emilygolden@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Rose', 'Mills', 'rosemills@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Franklin', 'Vaughan', 'franklinvaughan@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Margarita', 'Newman', 'margaritanewman@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Roberts', 'Trujillo', 'robertstrujillo@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Francisca', 'Mullins', 'franciscamullins@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Young', 'Holder', 'youngholder@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Pope', 'Wade', 'popewade@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Cantu', 'Ferrell', 'cantuferrell@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Wilkinson', 'Skinner', 'wilkinsonskinner@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Jenna', 'Ochoa', 'jennaochoa@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Josephine', 'Flowers', 'josephineflowers@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Genevieve', 'Mcguire', 'genevievemcguire@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Margery', 'Griffith', 'margerygriffith@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Gena', 'Nguyen', 'genanguyen@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Banks', 'Blankenship', 'banksblankenship@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Kayla', 'Marsh', 'kaylamarsh@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Robert', 'Murphy', 'robertmurphy@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Gonzales', 'Schneider', 'gonzalesschneider@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Felicia', 'Duncan', 'feliciaduncan@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Jasmine', 'Jensen', 'jasminejensen@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Cornelia', 'Mckee', 'corneliamckee@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Chaney', 'Sloan', 'chaneysloan@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Bethany', 'Rios', 'bethanyrios@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lancaster', 'Carlson', 'lancastercarlson@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Carr', 'Decker', 'carrdecker@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Mejia', 'Church', 'mejiachurch@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Christy', 'Spencer', 'christyspencer@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Lorie', 'Chen', 'loriechen@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Powell', 'Simpson', 'powellsimpson@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Ayala', 'Contreras', 'ayalacontreras@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Melton', 'Cannon', 'meltoncannon@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Marshall', 'Garrett', 'marshallgarrett@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Green', 'Sellers', 'greensellers@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Dominique', 'Cobb', 'dominiquecobb@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Blair', 'Bright', 'blairbright@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Mara', 'Elliott', 'maraelliott@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Wall', 'Reid', 'wallreid@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Tate', 'Robbins', 'taterobbins@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Sandoval', 'Morse', 'sandovalmorse@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Sweet', 'Shepard', 'sweetshepard@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Geraldine', 'Roy', 'geraldineroy@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Whitney', 'West', 'whitneywest@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Castro', 'Peters', 'castropeters@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Dee', 'Powell', 'deepowell@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Jeanne', 'Ratliff', 'jeanneratliff@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Clarissa', 'Lynn', 'clarissalynn@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Fletcher', 'Thomas', 'fletcherthomas@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Leta', 'Donaldson', 'letadonaldson@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Dorsey', 'Fisher', 'dorseyfisher@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Sosa', 'Hobbs', 'sosahobbs@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Henson', 'Bird', 'hensonbird@polarium.com');
INSERT INTO USER(first_name,last_name, email) VALUES ('Barry', 'Tate', 'barrytate@polarium.com');


INSERT INTO BOOK(title,stock) VALUES ('voluptate id sint', '10');
INSERT INTO BOOK(title,stock) VALUES ('enim Lorem eiusmod', '6');  
INSERT INTO BOOK(title,stock) VALUES ('do officia proident', '13');
INSERT INTO BOOK(title,stock) VALUES ('enim eiusmod ipsum', '6');  
INSERT INTO BOOK(title,stock) VALUES ('mollit nulla Lorem', '14'); 
INSERT INTO BOOK(title,stock) VALUES ('exercitation ex sint', '2');
INSERT INTO BOOK(title,stock) VALUES ('eu consequat labore', '0'); 
INSERT INTO BOOK(title,stock) VALUES ('Lorem irure cillum', '0');  
INSERT INTO BOOK(title,stock) VALUES ('est nostrud est', '13');    
INSERT INTO BOOK(title,stock) VALUES ('voluptate officia ut', '9');
INSERT INTO BOOK(title,stock) VALUES ('eu aute pariatur', '9');    
INSERT INTO BOOK(title,stock) VALUES ('esse occaecat et', '1');    
INSERT INTO BOOK(title,stock) VALUES ('aute sit voluptate', '13'); 
INSERT INTO BOOK(title,stock) VALUES ('qui nisi Lorem', '6');
INSERT INTO BOOK(title,stock) VALUES ('reprehenderit id pariatur', '9');
INSERT INTO BOOK(title,stock) VALUES ('veniam adipisicing excepteur', '10');
INSERT INTO BOOK(title,stock) VALUES ('amet qui minim', '4');
INSERT INTO BOOK(title,stock) VALUES ('id minim velit', '7');
INSERT INTO BOOK(title,stock) VALUES ('nostrud labore pariatur', '9');
INSERT INTO BOOK(title,stock) VALUES ('eu reprehenderit laborum', '2');
INSERT INTO BOOK(title,stock) VALUES ('duis adipisicing elit', '10');
INSERT INTO BOOK(title,stock) VALUES ('voluptate cillum voluptate', '15');
INSERT INTO BOOK(title,stock) VALUES ('ipsum eiusmod cillum', '2');
INSERT INTO BOOK(title,stock) VALUES ('ex duis reprehenderit', '13');
INSERT INTO BOOK(title,stock) VALUES ('ut ad exercitation', '10');
INSERT INTO BOOK(title,stock) VALUES ('esse reprehenderit adipisicing', '7');
INSERT INTO BOOK(title,stock) VALUES ('amet tempor enim', '10');
INSERT INTO BOOK(title,stock) VALUES ('ipsum culpa exercitation', '6');
INSERT INTO BOOK(title,stock) VALUES ('velit ad incididunt', '3');
INSERT INTO BOOK(title,stock) VALUES ('adipisicing ullamco qui', '2');
INSERT INTO BOOK(title,stock) VALUES ('aliquip ex dolor', '13');
INSERT INTO BOOK(title,stock) VALUES ('cillum incididunt duis', '11');
INSERT INTO BOOK(title,stock) VALUES ('amet eu non', '1');
INSERT INTO BOOK(title,stock) VALUES ('culpa nostrud fugiat', '14');
INSERT INTO BOOK(title,stock) VALUES ('ullamco reprehenderit reprehenderit', '14');
INSERT INTO BOOK(title,stock) VALUES ('Lorem laborum deserunt', '9');
INSERT INTO BOOK(title,stock) VALUES ('Lorem ipsum ad', '5');
INSERT INTO BOOK(title,stock) VALUES ('laborum exercitation fugiat', '1');
INSERT INTO BOOK(title,stock) VALUES ('enim labore qui', '14');
INSERT INTO BOOK(title,stock) VALUES ('eiusmod aliquip qui', '8');
INSERT INTO BOOK(title,stock) VALUES ('qui do nostrud', '11');
INSERT INTO BOOK(title,stock) VALUES ('do exercitation excepteur', '3');
INSERT INTO BOOK(title,stock) VALUES ('voluptate aliquip ea', '5');
INSERT INTO BOOK(title,stock) VALUES ('magna ex officia', '7');
INSERT INTO BOOK(title,stock) VALUES ('cupidatat eu culpa', '2');
INSERT INTO BOOK(title,stock) VALUES ('aliquip anim laboris', '3');
INSERT INTO BOOK(title,stock) VALUES ('cupidatat excepteur cupidatat', '10');
INSERT INTO BOOK(title,stock) VALUES ('duis excepteur eu', '7');
INSERT INTO BOOK(title,stock) VALUES ('dolore cupidatat enim', '14');
INSERT INTO BOOK(title,stock) VALUES ('consectetur officia aute', '4');
INSERT INTO BOOK(title,stock) VALUES ('est cillum ea', '10');
INSERT INTO BOOK(title,stock) VALUES ('eu exercitation sint', '6');
INSERT INTO BOOK(title,stock) VALUES ('ad sint quis', '4');
INSERT INTO BOOK(title,stock) VALUES ('laborum voluptate culpa', '13');
INSERT INTO BOOK(title,stock) VALUES ('officia minim do', '7');
INSERT INTO BOOK(title,stock) VALUES ('excepteur labore aliquip', '13');
INSERT INTO BOOK(title,stock) VALUES ('est duis ut', '12');
INSERT INTO BOOK(title,stock) VALUES ('ex veniam ex', '10');
INSERT INTO BOOK(title,stock) VALUES ('ad commodo nostrud', '4');
INSERT INTO BOOK(title,stock) VALUES ('magna laboris adipisicing', '2');
INSERT INTO BOOK(title,stock) VALUES ('ullamco voluptate ea', '7');
INSERT INTO BOOK(title,stock) VALUES ('amet quis ea', '10');
INSERT INTO BOOK(title,stock) VALUES ('aliqua ut consequat', '10');
INSERT INTO BOOK(title,stock) VALUES ('enim excepteur consectetur', '13');
INSERT INTO BOOK(title,stock) VALUES ('quis duis eu', '10');
INSERT INTO BOOK(title,stock) VALUES ('magna pariatur veniam', '5');
INSERT INTO BOOK(title,stock) VALUES ('consequat exercitation est', '7');
INSERT INTO BOOK(title,stock) VALUES ('do amet ea', '15');
INSERT INTO BOOK(title,stock) VALUES ('quis minim ullamco', '11');
INSERT INTO BOOK(title,stock) VALUES ('ipsum pariatur qui', '0');
INSERT INTO BOOK(title,stock) VALUES ('veniam nostrud cupidatat', '10');
INSERT INTO BOOK(title,stock) VALUES ('nisi esse consectetur', '11');
INSERT INTO BOOK(title,stock) VALUES ('anim labore nostrud', '0');
INSERT INTO BOOK(title,stock) VALUES ('dolor officia voluptate', '4');
INSERT INTO BOOK(title,stock) VALUES ('elit aliquip consectetur', '14');
INSERT INTO BOOK(title,stock) VALUES ('ea ad dolor', '12');
INSERT INTO BOOK(title,stock) VALUES ('elit voluptate dolore', '11');
INSERT INTO BOOK(title,stock) VALUES ('exercitation cillum tempor', '15');
INSERT INTO BOOK(title,stock) VALUES ('irure elit et', '2');
INSERT INTO BOOK(title,stock) VALUES ('irure excepteur amet', '12');
INSERT INTO BOOK(title,stock) VALUES ('enim reprehenderit ullamco', '13');
INSERT INTO BOOK(title,stock) VALUES ('mollit sunt mollit', '15');
INSERT INTO BOOK(title,stock) VALUES ('velit Lorem dolore', '8');
INSERT INTO BOOK(title,stock) VALUES ('occaecat Lorem dolor', '4');
INSERT INTO BOOK(title,stock) VALUES ('veniam incididunt eiusmod', '3');
INSERT INTO BOOK(title,stock) VALUES ('voluptate ut adipisicing', '1');
INSERT INTO BOOK(title,stock) VALUES ('eu aute dolore', '4');
INSERT INTO BOOK(title,stock) VALUES ('consequat magna veniam', '0');
INSERT INTO BOOK(title,stock) VALUES ('dolore cillum veniam', '7');
INSERT INTO BOOK(title,stock) VALUES ('enim officia occaecat', '12');
INSERT INTO BOOK(title,stock) VALUES ('sunt officia labore', '14');
INSERT INTO BOOK(title,stock) VALUES ('laboris aliqua ad', '3');
INSERT INTO BOOK(title,stock) VALUES ('nisi deserunt velit', '14');
INSERT INTO BOOK(title,stock) VALUES ('id et proident', '8');
INSERT INTO BOOK(title,stock) VALUES ('reprehenderit laboris eiusmod', '12');
INSERT INTO BOOK(title,stock) VALUES ('duis magna magna', '12');
INSERT INTO BOOK(title,stock) VALUES ('officia ullamco ut', '5');
INSERT INTO BOOK(title,stock) VALUES ('voluptate ut amet', '12');
INSERT INTO BOOK(title,stock) VALUES ('veniam officia cillum', '12');
INSERT INTO BOOK(title,stock) VALUES ('dolor exercitation consequat', '5');
INSERT INTO BOOK(title,stock) VALUES ('non aute culpa', '15');
INSERT INTO BOOK(title,stock) VALUES ('magna officia aliqua', '13');
INSERT INTO BOOK(title,stock) VALUES ('laboris deserunt deserunt', '2');
INSERT INTO BOOK(title,stock) VALUES ('dolore non elit', '0');
INSERT INTO BOOK(title,stock) VALUES ('ad reprehenderit sunt', '14');
INSERT INTO BOOK(title,stock) VALUES ('occaecat ea fugiat', '15');
INSERT INTO BOOK(title,stock) VALUES ('nostrud proident id', '7');
INSERT INTO BOOK(title,stock) VALUES ('aute ut cillum', '15');
INSERT INTO BOOK(title,stock) VALUES ('non aute mollit', '9');
INSERT INTO BOOK(title,stock) VALUES ('labore consectetur id', '12');
INSERT INTO BOOK(title,stock) VALUES ('qui pariatur quis', '2');
INSERT INTO BOOK(title,stock) VALUES ('Lorem nulla amet', '2');
INSERT INTO BOOK(title,stock) VALUES ('enim dolor esse', '14');
INSERT INTO BOOK(title,stock) VALUES ('Lorem esse id', '0');
INSERT INTO BOOK(title,stock) VALUES ('elit et id', '2');
INSERT INTO BOOK(title,stock) VALUES ('qui aute ut', '14');
INSERT INTO BOOK(title,stock) VALUES ('nisi adipisicing adipisicing', '1');
INSERT INTO BOOK(title,stock) VALUES ('duis eu aliquip', '4');
INSERT INTO BOOK(title,stock) VALUES ('qui nisi dolor', '11');
INSERT INTO BOOK(title,stock) VALUES ('tempor eu deserunt', '8');
INSERT INTO BOOK(title,stock) VALUES ('tempor et magna', '12');
INSERT INTO BOOK(title,stock) VALUES ('ullamco duis do', '10');
INSERT INTO BOOK(title,stock) VALUES ('aliqua exercitation sunt', '8');
INSERT INTO BOOK(title,stock) VALUES ('cillum ad reprehenderit', '10');
INSERT INTO BOOK(title,stock) VALUES ('duis laborum magna', '2');
INSERT INTO BOOK(title,stock) VALUES ('magna dolor aute', '12');
INSERT INTO BOOK(title,stock) VALUES ('nisi culpa pariatur', '11');
INSERT INTO BOOK(title,stock) VALUES ('laboris pariatur laboris', '12');
INSERT INTO BOOK(title,stock) VALUES ('adipisicing ut non', '9');
INSERT INTO BOOK(title,stock) VALUES ('enim irure labore', '0');
INSERT INTO BOOK(title,stock) VALUES ('in culpa nostrud', '4');
INSERT INTO BOOK(title,stock) VALUES ('nulla tempor magna', '14');
INSERT INTO BOOK(title,stock) VALUES ('dolore mollit culpa', '3');
INSERT INTO BOOK(title,stock) VALUES ('adipisicing aliquip consectetur', '14');
INSERT INTO BOOK(title,stock) VALUES ('do et laborum', '6');
INSERT INTO BOOK(title,stock) VALUES ('id officia fugiat', '5');
INSERT INTO BOOK(title,stock) VALUES ('Lorem magna sint', '5');
INSERT INTO BOOK(title,stock) VALUES ('aliquip consequat ut', '7');
INSERT INTO BOOK(title,stock) VALUES ('aliquip enim eu', '7');
INSERT INTO BOOK(title,stock) VALUES ('id anim duis', '4');
INSERT INTO BOOK(title,stock) VALUES ('exercitation ullamco incididunt', '9');
INSERT INTO BOOK(title,stock) VALUES ('laborum cupidatat tempor', '7');
INSERT INTO BOOK(title,stock) VALUES ('anim eu ullamco', '14');
INSERT INTO BOOK(title,stock) VALUES ('eu esse ea', '7');
INSERT INTO BOOK(title,stock) VALUES ('consequat id nostrud', '8');
INSERT INTO BOOK(title,stock) VALUES ('et ullamco ea', '3');
INSERT INTO BOOK(title,stock) VALUES ('consectetur aliquip incididunt', '8');
INSERT INTO BOOK(title,stock) VALUES ('do commodo duis', '4');
INSERT INTO BOOK(title,stock) VALUES ('aliqua laboris dolor', '15');
INSERT INTO BOOK(title,stock) VALUES ('minim ea esse', '11');


INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (145,69,'2022-7-17','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (8,94,'2022-8-12','renewal','on time');      
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (89,144,'2022-3-11','renewal','on delay');   
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (35,136,'2022-5-12','renewal','returned');   
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (62,47,'2022-4-15','renewal','returned');    
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (116,78,'2022-9-8','renewal','on time');     
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (45,22,'2022-10-10','borrowing','returned'); 
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (137,75,'2022-1-11','renewal','returned');   
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (134,65,'2022-10-15','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (91,101,'2022-6-8','borrowing','on time');   
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (33,104,'2022-7-12','renewal','returned');   
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (103,3,'2022-5-9','renewal','on delay');     
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (43,17,'2022-2-14','renewal','on delay');    
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (67,150,'2022-6-18','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (145,123,'2022-8-12','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (9,25,'2022-11-12','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (91,36,'2022-4-9','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (102,145,'2022-2-10','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (56,145,'2022-7-11','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (124,87,'2022-6-14','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (29,71,'2022-10-18','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (113,127,'2022-12-13','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (31,68,'2022-10-8','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (142,132,'2022-5-8','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (31,64,'2022-12-9','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (118,16,'2022-11-13','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (149,95,'2022-6-13','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (71,95,'2022-11-13','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (88,50,'2022-12-14','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (2,85,'2022-7-16','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (61,139,'2022-2-8','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (26,23,'2022-7-9','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (20,129,'2022-6-14','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (24,72,'2022-4-10','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (105,124,'2022-6-12','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (46,45,'2022-8-18','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (34,87,'2022-3-12','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (75,5,'2022-4-11','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (50,72,'2022-11-14','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (103,89,'2022-7-12','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (93,28,'2022-1-12','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (45,103,'2022-9-12','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (29,8,'2022-8-11','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (132,18,'2022-11-13','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (92,70,'2022-10-16','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (127,14,'2022-2-17','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (72,32,'2022-5-16','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (97,26,'2022-3-9','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (110,126,'2022-10-12','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (34,85,'2022-3-18','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (98,48,'2022-12-10','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (130,52,'2022-1-9','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (150,133,'2022-7-14','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (143,60,'2022-4-9','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (113,27,'2022-6-11','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (139,31,'2022-4-10','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (20,9,'2022-5-17','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (47,127,'2022-10-11','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (13,96,'2022-10-12','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (22,58,'2022-10-16','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (44,36,'2022-1-17','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (63,79,'2022-2-15','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (104,83,'2022-7-10','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (68,131,'2022-12-8','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (79,103,'2022-6-16','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (99,129,'2022-5-10','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (9,33,'2022-1-12','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (10,75,'2022-8-8','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (138,137,'2022-11-16','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (81,66,'2022-1-9','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (89,47,'2022-11-14','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (45,66,'2022-1-16','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (109,33,'2022-9-15','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (18,47,'2022-11-18','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (140,107,'2022-10-12','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (2,72,'2022-8-11','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (140,129,'2022-2-9','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (103,2,'2022-2-17','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (61,41,'2022-5-18','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (16,17,'2022-8-14','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (58,63,'2022-6-18','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (102,136,'2022-7-14','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (111,87,'2022-12-16','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (125,8,'2022-4-9','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (110,128,'2022-1-12','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (11,9,'2022-9-14','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (148,133,'2022-12-16','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (57,67,'2022-10-18','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (133,39,'2022-9-12','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (134,134,'2022-3-16','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (121,59,'2022-2-10','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (4,63,'2022-1-17','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (129,83,'2022-6-14','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (13,45,'2022-11-12','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (90,129,'2022-12-18','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (133,50,'2022-11-12','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (115,18,'2022-11-8','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (83,142,'2022-4-15','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (122,49,'2022-11-18','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (92,100,'2022-10-9','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (74,144,'2022-7-16','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (99,135,'2022-4-14','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (113,116,'2022-9-18','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (24,1,'2022-11-11','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (4,83,'2022-6-16','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (81,150,'2022-3-18','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (87,138,'2022-7-16','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (146,41,'2022-10-11','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (128,40,'2022-6-10','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (79,55,'2022-8-13','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (135,34,'2022-6-16','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (58,55,'2022-9-16','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (41,54,'2022-9-16','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (120,95,'2022-3-15','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (66,1,'2022-1-13','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (114,3,'2022-3-9','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (109,46,'2022-12-17','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (120,8,'2022-10-12','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (112,41,'2022-3-18','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (62,132,'2022-2-9','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (116,82,'2022-3-15','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (89,129,'2022-4-12','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (124,116,'2022-5-16','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (53,66,'2022-4-8','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (4,147,'2022-9-8','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (123,52,'2022-3-9','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (98,98,'2022-10-12','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (24,76,'2022-3-13','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (56,113,'2022-9-11','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (69,52,'2022-3-18','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (11,66,'2022-12-16','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (3,81,'2022-1-9','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (10,3,'2022-1-15','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (27,16,'2022-4-9','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (85,145,'2022-1-12','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (145,32,'2022-3-10','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (64,137,'2022-11-14','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (122,46,'2022-4-18','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (134,72,'2022-3-13','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (61,107,'2022-6-8','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (125,58,'2022-3-16','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (125,47,'2022-12-15','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (29,64,'2022-9-18','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (137,21,'2022-3-17','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (105,19,'2022-9-17','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (107,98,'2022-9-11','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (119,95,'2022-10-17','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (105,117,'2022-10-11','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (59,141,'2022-6-12','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (126,99,'2022-11-18','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (77,54,'2022-7-12','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (149,43,'2022-9-16','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (147,22,'2022-7-8','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (23,138,'2022-12-9','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (116,53,'2022-10-14','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (104,14,'2022-5-8','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (52,1,'2022-3-12','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (47,21,'2022-7-11','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (94,24,'2022-7-13','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (134,118,'2022-9-15','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (72,29,'2022-11-18','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (135,54,'2022-6-10','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (5,71,'2022-2-17','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (50,50,'2022-8-8','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (139,19,'2022-2-18','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (144,68,'2022-3-11','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (34,82,'2022-9-13','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (29,9,'2022-7-18','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (96,85,'2022-12-13','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (124,114,'2022-7-16','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (49,66,'2022-1-10','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (1,68,'2022-3-16','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (99,18,'2022-8-12','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (42,64,'2022-5-17','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (147,111,'2022-3-8','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (117,13,'2022-10-16','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (138,30,'2022-5-14','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (117,49,'2022-7-15','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (135,10,'2022-12-12','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (49,124,'2022-9-14','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (147,150,'2022-6-15','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (119,112,'2022-7-13','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (133,109,'2022-8-13','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (8,44,'2022-3-15','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (52,8,'2022-4-8','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (14,130,'2022-4-8','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (135,26,'2022-2-13','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (146,8,'2022-5-14','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (71,127,'2022-5-13','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (122,24,'2022-3-17','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (38,75,'2022-12-9','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (112,136,'2022-12-9','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (22,86,'2022-4-12','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (107,26,'2022-3-14','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (128,20,'2022-1-18','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (119,33,'2022-9-15','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (45,93,'2022-2-8','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (27,13,'2022-9-16','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (100,89,'2022-1-14','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (132,23,'2022-8-11','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (87,50,'2022-10-13','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (110,140,'2022-7-8','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (148,123,'2022-10-8','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (75,54,'2022-9-18','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (49,115,'2022-5-17','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (46,35,'2022-11-15','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (91,69,'2022-10-12','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (80,71,'2022-5-11','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (105,87,'2022-3-8','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (119,20,'2022-2-16','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (116,37,'2022-7-16','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (88,140,'2022-3-14','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (115,108,'2022-3-16','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (138,28,'2022-7-13','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (87,147,'2022-12-14','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (27,133,'2022-5-14','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (2,25,'2022-2-13','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (87,148,'2022-3-8','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (20,111,'2022-3-14','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (113,93,'2022-2-13','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (29,52,'2022-7-11','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (144,150,'2022-8-18','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (23,9,'2022-12-8','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (86,124,'2022-9-17','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (138,69,'2022-6-14','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (7,149,'2022-3-13','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (59,28,'2022-7-9','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (140,142,'2022-12-11','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (137,61,'2022-4-12','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (47,66,'2022-1-8','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (36,114,'2022-1-11','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (54,89,'2022-6-13','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (134,48,'2022-11-15','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (124,104,'2022-5-18','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (27,124,'2022-3-18','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (18,32,'2022-1-10','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (99,48,'2022-1-18','borrowing','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (129,119,'2022-5-12','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (16,5,'2022-1-16','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (35,74,'2022-6-13','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (82,56,'2022-1-18','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (6,24,'2022-1-12','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (57,123,'2022-2-10','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (68,128,'2022-4-12','renewal','on delay');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (139,37,'2022-6-12','borrowing','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (119,84,'2022-9-13','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (3,77,'2022-2-18','borrowing','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (31,118,'2022-10-17','renewal','returned');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (61,127,'2022-5-9','renewal','on time');
INSERT INTO LOAN(fk_id_user,fk_id_book,start_date,type,status) VALUES (82,96,'2022-6-18','renewal','on delay');